Add First Iteration of Documentation of SDC Pipeline
HERMES-SOC/sdc_aws_pipeline_architecture pull request #10
Opened 2022-11-21 18:03 UTC by dbarrous

This PR includes the first iteration of the documentation of the SDC Pipeline architecture for review and feedback. It also adds the proper CI/CD tests for the automated doc building.

You can view the built docs here: https://sdc-aws-pipeline-architecture.readthedocs.io/en/add-docs/index.html

2022-11-21 19:36 UTC, acrager requested changes

2022-11-22 18:32 UTC, dbarrous commented on docs/pipeline-diagrams.rst
> +** Going to redo this as a normal image, because graphviz makes it look a bit too small and hard to read. **
Fixed in the most recent commit, ty!

2022-11-22 18:33 UTC, dbarrous commented on docs/user-guide/aws-tag-overview.rst
> +How we use Tags
Fixed in the most recent commit, ty!

2022-11-22 18:33 UTC, dbarrous commented on docs/user-guide/index.rst
> +* AWS Cli installed and configured
Fixed in the most recent commit, ty!

2022-11-23 15:26 UTC, acrager approved these changes
Thanks! Diagrams render correctly, formatting in text looks great.

2022-12-07 14:48 UTC, merged