Move variables to a config file and out of a code file (vars.py)
HERMES-SOC/sdc_aws_pipeline_architecture pull request #9
Opened 2022-11-14 15:13 UTC by dbarrous

This PR moves the variables that were declared within the `vars.py` file into a `config.yaml` file. This should make it a bit easier to fork and configure.

2022-11-14 17:49 UTC, ehsteve requested changes
This looks good overall. Just have a few suggested changes.

2022-11-14 17:49 UTC, ehsteve commented on app.py
> -from cdk_deployment.vars import DEPLOYMENT_REGION
don't you still need this. you still use this in line 58 and 78.

2022-11-14 17:49 UTC, ehsteve commented on app.py
> +    with open("./config.yaml", "r") as f:
maybe make this bit a function that returns a dictionary? that way if we want to support other file types for the config file it would be easier to do so.

2022-11-14 17:49 UTC, ehsteve commented on cdk_deployment/sdc_aws_pipeline_architecture.py
> +            database_name=config["TIMESTREAM_DATABASE_NAME"],
how about adding a function that validates the config dictionary? Maybe it is not necessary since this code would fail if the key does not exist but it may not be worth running any of the code if the config file is broken. Even better, this validator could be used in the testing suite.

2022-11-14 17:49 UTC, ehsteve commented on config.yaml
> +MISSION_PKG: hermes_core
how would we support a configuration with only one python package because the mission only has one instrument or all code for the multiple instruments lives in the same package?

2022-11-14 19:57 UTC, acrager submitted a review, later dismissed
Reviewed as a team during the SDC Office hours. Agree with the yaml methodology and saw no problems with the code.

2022-11-15 19:11 UTC, dbarrous commented on app.py
> -from cdk_deployment.vars import DEPLOYMENT_REGION
It uses the config dict instead now

2022-11-15 19:13 UTC, dbarrous commented on config.yaml
> +MISSION_PKG: hermes_core
I think we could add a flag in the future that could trigger the pipeline to utilize the singular package instead of the separate package configuration instead.

2022-11-17 15:36 UTC, ehsteve approved these changes
These updates look good to me!

2022-11-21 16:36 UTC, acrager commented on cdk_deployment/sdc_aws_processing_lambda.py
> +            for data_level in config["VALID_DATA_LEVELS"]:
just want to confirm that both vars and util are now represented by config.

2022-11-21 16:38 UTC, acrager approved these changes
Left one comment that was more a question to double check. Not something to hold you back on merging once you've checked.

2022-11-21 17:26 UTC, dbarrous commented on cdk_deployment/sdc_aws_processing_lambda.py
> +            for data_level in config["VALID_DATA_LEVELS"]:
Yup, VALID_DATA_LEVELS are now handled in the config

2022-11-21 17:27 UTC, merged